# Generated by Django 6.0.3 on 2026-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPPER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('ltp', models.FloatField()),
                ('close_ltp', models.FloatField()),
                ('close_ltp_percent', models.FloatField()),
                ('vwap', models.FloatField()),
                ('vol', models.BigIntegerField()),
                ('prev_close', models.FloatField()),
                ('turnover', models.FloatField()),
                ('transactions', models.IntegerField()),
                ('diff', models.FloatField()),
                ('range_value', models.FloatField()),
                ('change_percent', models.FloatField()),
                ('range_percent', models.FloatField()),
                ('vwap_percent', models.FloatField()),
                ('weeks_52_high', models.FloatField()),
                ('weeks_52_low', models.FloatField()),
                ('date', models.DateField()),
                ('days_120', models.FloatField(blank=True, null=True)),
                ('days_180', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
