# Generated by Django 6.0.3 on 2026-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upper',
            name='vol',
            field=models.FloatField(),
        ),
    ]
