# Generated by Django 6.0.3 on 2026-04-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0002_alter_upper_vol'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('absolute_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('week_52_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_52_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turnover_values', models.DecimalField(decimal_places=2, max_digits=20)),
                ('turnover_volume', models.BigIntegerField()),
                ('total_transaction', models.BigIntegerField()),
            ],
        ),
    ]
