# Generated by Django 6.0.3 on 2026-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0005_nepseindexdata_change_nepseindexdata_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostActiveStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('security_id', models.IntegerField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=12)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=20)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_traded_quantity', models.BigIntegerField()),
            ],
        ),
    ]
