# Generated by Django 6.0.3 on 2026-04-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0006_mostactivestocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostactivestocks',
            name='security_id',
            field=models.IntegerField(),
        ),
    ]
