# Generated by Django 6.0.3 on 2026-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0007_alter_mostactivestocks_security_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepseindex',
            name='scripts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
