# Generated by Django 6.0.3 on 2026-04-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0008_nepseindex_scripts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(max_length=255)),
                ('security_id', models.IntegerField()),
                ('ltp', models.FloatField()),
                ('cp', models.FloatField()),
                ('point_change', models.FloatField()),
                ('percentage_change', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Loser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('symbol', models.CharField(max_length=20)),
                ('security_name', models.CharField(max_length=255)),
                ('security_id', models.IntegerField()),
                ('ltp', models.FloatField()),
                ('cp', models.FloatField()),
                ('point_change', models.FloatField()),
                ('percentage_change', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('total_listed', models.IntegerField()),
                ('advancing', models.IntegerField()),
                ('declining', models.IntegerField()),
                ('unchanged', models.IntegerField()),
                ('positive_circuit', models.IntegerField()),
                ('negative_circuit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sector_id', models.IntegerField()),
                ('index_name', models.CharField(max_length=150)),
                ('current_value', models.FloatField()),
                ('change', models.FloatField()),
                ('percentage_change', models.FloatField()),
            ],
        ),
    ]
