# Generated by Django 6.0.3 on 2026-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0009_gainer_loser_marketbreadth_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gainer',
            name='cp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gainer',
            name='ltp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gainer',
            name='percentage_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gainer',
            name='point_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loser',
            name='cp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loser',
            name='ltp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loser',
            name='percentage_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loser',
            name='point_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='advancing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='declining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='negative_circuit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='positive_circuit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='total_listed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbreadth',
            name='unchanged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='percentage_change',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
