# Generated by Django 6.0.3 on 2026-04-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0010_alter_gainer_cp_alter_gainer_ltp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('up', models.BooleanField()),
            ],
        ),
    ]
