# Generated by Django 6.0.3 on 2026-05-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0011_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='traded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='traded_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
