# Generated by Django 6.0.3 on 2026-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0012_stockdata_high_stockdata_low_stockdata_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='previous_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
